# work_dir: ./work_dir/ntu120/oneshot/lst_joint

# feeder
feeder: feeders.feeder_ntu.Feeder
train_feeder_args:
  data_path: data/ntu_all_os/NTU_ALL_OS_train.npz
  split: train
  debug: False
  random_choose: False
  random_shift: False
  random_move: False
  window_size: 64
  normalization: False
  random_rot: True
  p_interval: [0.5, 1]
  vel: False
  bone: False

test_feeder_args:
  data_path: data/ntu_all_os/NTU_ALL_OS_test.npz
  split: test
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False

examplar_feeder_args:
  data_path: data/ntu_all_os/NTU_ALL_OS_examplar.npz
  split: examplar
  window_size: 64
  p_interval: [0.95]
  vel: False
  bone: False
  debug: False

# model
model: model.ctrgcn.Model
model_args:
  num_class: 120
  num_point: 25
  num_person: 2
  graph: graph.ntu_rgb_d.Graph
  k: 8
  head: ['ViT-B/32']
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0005
base_lr: 0.1
lr_decay_rate: 0.1
step: [25,35] # [90, 100] 
warm_up_epoch: 5

# training
batch_size: 100
test_batch_size: 100
num_epoch: 40
nesterov: True
